image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - nodejs
  - hut
environment:
  site: ihavea.quest
  # https://docs.npmjs.com/cli/v6/using-npm/config#progress
  CI: true
tasks:
  - install: |
      cd $site
      npm install
  - package: |
      cd $site
      npm run build
      tar -C _site -cvz . > ../site.tar.gz
  - upload: |
      hut pages publish -d $site site.tar.gz
